name: getagriculture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  share: ^2.0.4
  http: ^1.1.2
  mongo_dart: ^0.9.4
  auto_size_text: ^3.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/borsa/
    - assets/images/
    - assets/images/profil/
    - assets/images/news/
    - assets/images/main/
    - assets/images/weather/